// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9LOPxyAo3kAnhsBncH0LHdFBZoTBayOY',
    appId: '1:439869257285:android:a593e0814c318bcd9c152c',
    messagingSenderId: '439869257285',
    projectId: 'shopsmartly-dcc7e',
    storageBucket: 'shopsmartly-dcc7e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2S-_CSdL6ieYZ_ysXYmlOD-216aGcHg',
    appId: '1:439869257285:ios:cc8b6dc1614ae2ed9c152c',
    messagingSenderId: '439869257285',
    projectId: 'shopsmartly-dcc7e',
    storageBucket: 'shopsmartly-dcc7e.appspot.com',
    iosClientId: '439869257285-olq54isnsbngssvct3lifo5b1m5dhnei.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsmartly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN2S-_CSdL6ieYZ_ysXYmlOD-216aGcHg',
    appId: '1:439869257285:ios:44fe81ff1cc9a80c9c152c',
    messagingSenderId: '439869257285',
    projectId: 'shopsmartly-dcc7e',
    storageBucket: 'shopsmartly-dcc7e.appspot.com',
    iosClientId: '439869257285-bpmg1unhtvf59hktab18fn6hjpo4jkll.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopsmartly.RunnerTests',
  );
}
